### PR TITLE
Fixed compiler error

### PR DESCRIPTION
**Pull request by TannerMoore**
Unity version: 2018.3.8f1

### CODE REVIEW

**Comment by Seanba** [comment]
Hmmm ... I'm not seeing a compiler error that necessitates this fix. I'll need to look into why this is needed for you.

**Comment by TannerMoore** [comment]
I added in the Unity version to help reproduce it. I think in the past, Unity has made changes to their underlying compilers/libraries that can cause issues like this one.

**Comment by Seanba** [comment]
Ah, it looks to me that you may have your player settings using .NET 3.5 Framework. Thanks for the PR.

**Comment by TannerMoore** [comment]
Woah I didn't even know that was a thing. I updated my .NET framework version accordingly

**Pull request closed without merging**
